#!/bin/bash

NOW_IMPORT=`(date --date='now' "+%Y-%m-%d %H:%M:%S")`
time_file=`(date --date='- '${1}' day' '+%d-%m-%Y')`

_LOGF=/home/mapuser/logs/history.log
export _LOGF


_file_path="/home/mapuser/reconcile.csv";
echo ${_file_path}


mysql -u reconciledb -h xx.xx.xx.59  reconcile -p'pbwC8gQmCy28RBRU#'<<EOF


LOAD DATA LOCAL INFILE '${_file_path}' IGNORE
INTO TABLE reconcile
CHARACTER SET tis620 
FIELDS TERMINATED BY ',' ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(USERNAME,STATUS_RADIUS,LASTLOGINDATE,EXPIRYDATE,CUSTOMERID,SERVICENO,USAGETIME,DOWNLOAD,UPLOAD,DATEOPER,ZONE_ID,PROVINCE_NAME,ACCOUNT_NUM,OFFERING_ID,OFFERING_NAME,OFFERING_PRICE,CNT_ONLINE)
SET
    	USERNAME = USERNAME,
	STATUS_RADIUS = STATUS_RADIUS,
	LASTLOGINDATE = LASTLOGINDATE,
	EXPIRYDATE = EXPIRYDATE,
	CUSTOMERID = CUSTOMERID,
	SERVICENO = SERVICENO,
	USAGETIME = USAGETIME,
	DOWNLOAD = DOWNLOAD,
	UPLOAD = UPLOAD,
	DATEOPER = DATEOPER,
	ZONE_ID = ZONE_ID,
	PROVINCE_NAME = PROVINCE_NAME,
	ACCOUNT_NUM = ACCOUNT_NUM,
	OFFERING_ID = OFFERING_ID,
	OFFERING_NAME = OFFERING_NAME,
	OFFERING_PRICE = OFFERING_PRICE,
	CNT_ONLINE = CNT_ONLINE
    
EOF